/**
 * DEML Learning Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface DesktopAuthOut {
  status: string;
  user: string;
  email: string;
  user_id: number;
  role: string;
  desktop_token?: string | null;
}
