/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface E2EEncryptionOut {
  transit: string;
  rest: string;
  clientPayload: string;
  rotationDaysRemaining: number;
}
