/**
 * DEML Learning Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EncryptionOptions {
  mode?: EncryptionOptions.ModeEnum;
  algo?: EncryptionOptions.AlgoEnum;
}
export namespace EncryptionOptions {
  export const ModeEnum = {
    E2ee: 'e2ee',
  } as const;
  export type ModeEnum = (typeof ModeEnum)[keyof typeof ModeEnum];
  export const AlgoEnum = {
    Aes256Gcm: 'aes-256-gcm',
  } as const;
  export type AlgoEnum = (typeof AlgoEnum)[keyof typeof AlgoEnum];
}
