/**
 * DEML Learning Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface EncryptedEnvelope {
  algo?: EncryptedEnvelope.AlgoEnum;
  key_id: string;
  nonce: string;
  ciphertext: string;
  ciphertext_sha256: string;
  ratchet_header?: string | null;
}
export namespace EncryptedEnvelope {
  export const AlgoEnum = {
    Aes256Gcm: 'aes-256-gcm',
  } as const;
  export type AlgoEnum = (typeof AlgoEnum)[keyof typeof AlgoEnum];
}
