/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IncidentOut {
  id: string;
  title: string;
  message: string;
  status: string;
  created_at: string;
  updated_at: string;
  status_page_id: string;
}
