/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IntegrationStatus {
  integration: string;
  status: string;
  enabled: boolean;
  version?: string | null;
  message?: string | null;
}
