/**
 * DEML BACKEND APP API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IntegrationOut {
  id: string;
  provider: string;
  active: boolean;
  last_sync?: string | null;
  created_at: string;
}
