/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ISACSubmissionOut {
  status: string;
  message: string;
  submission_id: string;
  mode: string;
  sent_payload: { [key: string]: any };
  logs: Array<string>;
}
