/**
 * DEML Learning Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface IssueReportPayload {
  client_report_id?: string;
  user_description: string;
  telemetry_context?: { [key: string]: any };
}
