/**
 * DEML BACKEND APP API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface LatestRunOut {
  status: string;
  message?: string | null;
  average_sla?: number | null;
  loss?: number | null;
  created_at?: string | null;
}
