/**
 * DEML BACKEND APP API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface MonitoredServiceOut {
  id: string;
  name: string;
  url: string;
  status_page_id: string;
  created_at: string;
  status?: string | null;
  sla?: number | null;
}
