/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PQKeyExchangeResponse {
  status: string;
  key_id?: string | null;
  public_key_b64?: string | null;
  message: string;
}
