/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PredictResponse {
  status: string;
  predictions: Array<number>;
  model_version: string;
  latency_ms: number;
}
