/**
 * DEML Learning Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EncryptedEnvelope } from './encryptedEnvelope';
import { EncryptionOptions } from './encryptionOptions';

/**
 * The only event shape DEML may forward to FORJD today.
 */
export interface SealedEvent {
  tenant_id: string;
  client_event_id: string;
  content_type?: SealedEvent.ContentTypeEnum;
  event_type?: SealedEvent.EventTypeEnum;
  schema_version?: number;
  workflow_id?: SealedEvent.WorkflowIdEnum;
  encryption?: EncryptionOptions;
  envelope: EncryptedEnvelope;
  metadata?: { [key: string]: any };
}
export namespace SealedEvent {
  export const ContentTypeEnum = {
    ApplicationForjdTelemetryv1: 'application/forjd-telemetry+v1',
  } as const;
  export type ContentTypeEnum = (typeof ContentTypeEnum)[keyof typeof ContentTypeEnum];
  export const EventTypeEnum = {
    DemlMetric: 'deml.metric',
    DemlAlert: 'deml.alert',
  } as const;
  export type EventTypeEnum = (typeof EventTypeEnum)[keyof typeof EventTypeEnum];
  export const WorkflowIdEnum = {
    DemlTelemetry: 'deml_telemetry',
  } as const;
  export type WorkflowIdEnum = (typeof WorkflowIdEnum)[keyof typeof WorkflowIdEnum];
}
