/**
 * DEML Learning Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SessionRegisterIn {
  session_id: string;
  user_agent?: string;
}
