/**
 * DEML Learning Platform API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SessionOut {
  session_id: string;
  user_agent?: string;
  ip?: string;
  created_at?: number;
  last_seen?: number;
}
