/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { E2EEncryptionOut } from './e2EEncryptionOut';
import { SOCCriteria } from './sOCCriteria';

export interface SOCStatusOut {
  status: string;
  overall_score: number;
  criteria: Array<SOCCriteria>;
  e2e_encryption?: E2EEncryptionOut | null;
}
