/**
 * DEML BACKEND APP API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface StatusPageIn {
  title: string;
  slug: string;
  description?: string | null;
  is_published?: boolean | null;
  google_analytics_id?: string | null;
  microsoft_clarity_id?: string | null;
  cloudflare_analytics_id?: string | null;
}
