/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UptimeDaySchema } from './uptimeDaySchema';

export interface StatusPageOut {
  id: string;
  title: string;
  slug: string;
  description: string;
  is_published: boolean;
  google_analytics_id?: string | null;
  microsoft_clarity_id?: string | null;
  cloudflare_analytics_id?: string | null;
  created_at: string;
  user_id?: number | null;
  cumulative_sla?: number | null;
  overall_uptime?: number | null;
  uptime_history?: UptimeDaySchema[] | null;
  p99_latency?: number | null;
  total_requests?: number | null;
}
