/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface STIXBundleOut {
  type: string;
  id: string;
  objects: Record<string, any>[];
}
