/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface SuccessSchema {
  status: string;
  user?: string | null;
  user_id?: number | null;
  role?: string | null;
}
