/**
 * DEML BACKEND APP API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TelemetryDualStreamPayload {
  tenant_id: string;
  url?: string | null;
  stream_type: string;
  tech_name?: string | null;
  version?: string | null;
  manifest_type?: string | null;
  manifest_content?: string | null;
}
