/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TelemetryPayload {
  url: string;
  status_code: number;
  response_time_ms: number;
  ip_address: string;
  is_active: boolean;
  telemetry_context?: Record<string, any> | null;
}
