/**
 * DEML BACKEND APP API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ThreatReportOut {
  status: string;
  anomaly_score?: number | null;
  top_location?: string | null;
  location_weight?: number | null;
  suspicious_ratio?: number | null;
  created_at?: string | null;
  message?: string | null;
}
