/**
 * Web Application API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TrainOut {
  status: string;
  message?: string | null;
  average_sla?: number | null;
  loss?: number | null;
  run_id?: string | null;
}
