/**
 * DEML BACKEND APP API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UptimeDaySchema {
  date: string;
  status: string;
  uptime: number | null;
}
