receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
        cors:
          allowed_origins:
            - "${env:ALLOWED_CORS_ORIGINS}" # Expects a specific domain like "https://dataengineeringformachinelearning.com"
          allowed_headers:
            - "Content-Type"
      grpc:
        endpoint: "0.0.0.0:4317"

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  clickhouse:
    endpoint: tcp://${env:CLICKHOUSE_HOST}:9000?dial_timeout=10s&compress=true
    username: ${env:CLICKHOUSE_USER}
    password: '${env:CLICKHOUSE_PASSWORD}'
    database: otel
    ttl: 720h # 30 days

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
