"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import firebase_admin
from dotenv import load_dotenv
from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a .env file located at the BASE_DIR (backend/)
load_dotenv(BASE_DIR / ".env", override=False)


# fmt: off
def clean_private_key(key: str) -> str:
  if not key:
    return key
  key = key.replace("\\n", "\n")
  import re
  begin_tag = "-----BEGIN " + "PRIVATE KEY-----\n"
  end_tag = "\n-----END " + "PRIVATE KEY-----"
  match = re.search(rf'({begin_tag})(.*?)({end_tag})', key, re.DOTALL)
  if match:
      header = match.group(1)
      body = match.group(2)
      footer = match.group(3)
      b64_chars = re.sub(r'\s+', '', body)
      missing_padding = len(b64_chars) % 4
      if missing_padding:
          body += '=' * (4 - missing_padding)
      key = header + body + footer
  return key
# fmt: on


# Write GCP service account JSON from environment variable to a file if provided
gcp_sa_json = os.getenv("GCP_SERVICE_ACCOUNT_JSON")
if gcp_sa_json:
  gcp_sa_json_clean = gcp_sa_json.strip()
  if gcp_sa_json_clean.startswith('"') and gcp_sa_json_clean.endswith('"'):
    import json

    try:
      # Strip potential double JSON encoding wrapper
      decoded = json.loads(gcp_sa_json_clean)
      if isinstance(decoded, str):
        gcp_sa_json_clean = decoded
    except Exception:
      pass

  # Clean double-escaped backslashes in private_key if present
  try:
    import json

    parsed = json.loads(gcp_sa_json_clean)
    if isinstance(parsed, str):
      parsed = json.loads(parsed)
    if "private_key" in parsed:
      parsed["private_key"] = clean_private_key(parsed["private_key"])
    gcp_sa_json_clean = json.dumps(parsed)
  except Exception:
    pass

  # Write to /tmp/gcp-service-account.json and set the standard env var path
  temp_credentials_path = "/tmp/gcp-service-account.json"
  try:
    with open(temp_credentials_path, "w") as f:
      f.write(gcp_sa_json_clean)
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = temp_credentials_path
  except Exception as e:
    import logging

    logging.getLogger("django").warning("Failed to write GCP JSON file: %s", e)


import sentry_sdk

sentry_sdk.init(
  dsn=os.getenv(
    "SENTRY_DSN",
    "https://4b412fe87313bb20e0a4785e4404ad34@o4511437520044032.ingest.us.sentry.io/4511556294541312",
  ),
  send_default_pii=True,
)

# Initialize Firebase Admin
if not firebase_admin._apps:
  service_account_json = os.getenv("FIREBASE_SERVICE_ACCOUNT_JSON")
  firebase_project_id = (
    os.getenv("FIREBASE_PROJECT_ID") or os.getenv("GOOGLE_CLOUD_PROJECT") or "demldotcom"
  )
  if service_account_json:
    import json

    try:
      # Strip any potential outer quote wrapping if present
      raw_json = service_account_json.strip()
      if raw_json.startswith('"') and raw_json.endswith('"'):
        try:
          # Parse out of the wrapper string
          raw_json = json.loads(raw_json)
        except Exception:
          pass

      cred_dict = json.loads(raw_json)
      if isinstance(cred_dict, str):
        cred_dict = json.loads(cred_dict)

      # Clean double-escaped backslashes in private_key if present
      if "private_key" in cred_dict:
        cred_dict["private_key"] = clean_private_key(cred_dict["private_key"])

      cred = credentials.Certificate(cred_dict)
      firebase_admin.initialize_app(cred)
    except Exception as e:
      import logging

      logging.getLogger("django").error(
        "Failed to initialize Firebase with service account JSON: %s", e
      )
      # Fallback with explicit project ID to avoid hanging on GCP metadata server lookups in non-GCP environments
      firebase_admin.initialize_app(options={"projectId": firebase_project_id})
  else:
    cred_path = BASE_DIR / "firebase-service-account.json"
    if cred_path.exists():
      cred = credentials.Certificate(str(cred_path))
      firebase_admin.initialize_app(cred)
    else:
      # Fallback with explicit project ID to avoid hanging on GCP metadata server lookups in non-GCP environments
      firebase_admin.initialize_app(options={"projectId": firebase_project_id})


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
  "SECRET_KEY", "django-insecure-izn^)q(e0k=rklyawiv0*4(unp)%4%@v54**mnt!@tw!thaub9"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
  host.strip().strip('"').strip("'")
  for host in os.getenv("ALLOWED_HOSTS", "*").split(",")
  if host.strip()
]


# Application definition

INSTALLED_APPS = [
  "daphne",
  "django.contrib.auth",
  "django.contrib.contenttypes",
  "django.contrib.sessions",
  "django.contrib.messages",
  "django.contrib.staticfiles",
  "django.contrib.sitemaps",
  "corsheaders",
  "whitenoise.runserver_nostatic",
  "django_migration_linter",
  "monitor",
  "ml",
  "telemetry",
]

MIDDLEWARE = [
  "django.middleware.security.SecurityMiddleware",
  "whitenoise.middleware.WhiteNoiseMiddleware",
  "corsheaders.middleware.CorsMiddleware",
  "django.middleware.common.CommonMiddleware",
  "django.middleware.csrf.CsrfViewMiddleware",
  "config.middleware.FirebaseAuthenticationMiddleware",
  "telemetry.middleware.NetworkTelemetryMiddleware",
  "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
  {
    "BACKEND": "django.template.backends.django.DjangoTemplates",
    "DIRS": [BASE_DIR / "templates"],
    "APP_DIRS": True,
    "OPTIONS": {
      "context_processors": [
        "django.template.context_processors.request",
      ],
    },
  },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

DRAGONFLY_HOST = os.getenv("DRAGONFLY_HOST", "deml-dragonfly.railway.internal")

# Channels
CHANNEL_LAYERS = {
  "default": {
    "BACKEND": "channels_redis.core.RedisChannelLayer",
    "CONFIG": {
      "hosts": [(DRAGONFLY_HOST, 6379)],
    },
  },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Gracefully fall back to local SQLite if DATABASE_URL is empty or does not start with a valid scheme
db_url = os.getenv("DATABASE_URL", "")
valid_schemes = (
  "sqlite://",
  "postgres://",
  "postgresql://",
  "mysql://",
  "cockroach://",
  "oracle://",
  "redshift://",
  "mssql://",
)
if not db_url or not any(db_url.startswith(scheme) for scheme in valid_schemes):
  os.environ["DATABASE_URL"] = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"

DATABASES = {
  "default": dj_database_url.config(
    conn_max_age=600,
    conn_health_checks=True,
  )
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
  },
  {
    "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
  },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

cors_allowed_origins = os.getenv("CORS_ALLOWED_ORIGINS", "")
CORS_ALLOWED_ORIGINS = (
  [origin.strip() for origin in cors_allowed_origins.split(",")] if cors_allowed_origins else []
)
if "https://dataengineeringformachinelearning.com" not in CORS_ALLOWED_ORIGINS:
  CORS_ALLOWED_ORIGINS.append("https://dataengineeringformachinelearning.com")

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = [
  *default_headers,
  "cache-control",
  "pragma",
  "expires",
]

CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:4200")

# Stripe Settings
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

# Security Headers & Cookie Settings
if not DEBUG:
  SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
  SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "True").lower() == "true"
  SESSION_COOKIE_SECURE = True
  CSRF_COOKIE_SECURE = True
  SECURE_HSTS_SECONDS = 31536000  # 1 year
  SECURE_HSTS_INCLUDE_SUBDOMAINS = True
  SECURE_HSTS_PRELOAD = True

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"


# Google OAuth Analytics Integration Settings
GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID", "mock-client-id")
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", "mock-client-secret")
GOOGLE_OAUTH_REDIRECT_URI = os.getenv(
  "GOOGLE_OAUTH_REDIRECT_URI",
  "http://localhost:8000/api/v1/system-status/integrations/google/callback",
)

# App versioning configuration
VERSION_PATH = BASE_DIR.parent / "version.txt"
LOCAL_VERSION_PATH = BASE_DIR / "version.txt"
if VERSION_PATH.exists():
  with open(VERSION_PATH) as f:
    APP_VERSION = f.read().strip()
elif LOCAL_VERSION_PATH.exists():
  with open(LOCAL_VERSION_PATH) as f:
    APP_VERSION = f.read().strip()
else:
  APP_VERSION = "0.0.0-dev"

# Centralized Logging Configuration
LOGGING = {
  "version": 1,
  "disable_existing_loggers": False,
  "formatters": {
    "verbose": {
      "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
      "style": "{",
    },
    "simple": {
      "format": "{levelname} {message}",
      "style": "{",
    },
  },
  "handlers": {
    "console": {
      "class": "logging.StreamHandler",
      "formatter": "simple",
    },
  },
  "loggers": {
    "django": {
      "handlers": ["console"],
      "level": "INFO",
    },
    "monitor.audit": {
      "handlers": ["console"],
      "level": "INFO",
      "propagate": True,
    },
  },
}

GCP_LOGGING_ENABLED = os.getenv("GCP_LOGGING_ENABLED", "False").lower() == "true"
if GCP_LOGGING_ENABLED:
  try:
    import google.cloud.logging

    gcp_client = google.cloud.logging.Client()
    LOGGING["handlers"]["gcp"] = {
      "class": "google.cloud.logging.handlers.CloudLoggingHandler",
      "client": gcp_client,
      "name": "audit_logs",
    }
    LOGGING["loggers"]["monitor.audit"]["handlers"].append("gcp")
  except Exception as e:
    import logging

    logging.getLogger("django").warning("Failed to initialize Google Cloud Logging: %s", e)


# Migration Linter Configuration
MIGRATION_LINTER_OPTIONS = {
  "ignore_initial_migrations": True,
  "ignore_name": [
    "0002_alter_endpoints_ip_address_statuspage_and_more",
    "0005_statuspage_is_published",
    "0009_rename_model_to_ml",
  ],
}
