# Generated by Django 6.0.3 on 2026-06-13 06:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class CreateTableIfNotExists(migrations.CreateModel):
  def database_forwards(self, app_label, schema_editor, from_state, to_state):
    table_name = self.options.get("db_table", f"{app_label}_{self.name.lower()}")
    if table_name in schema_editor.connection.introspection.table_names():
      return
    super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):
  dependencies = [
    ("ml", "0002_trainingrun_status_page"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    CreateTableIfNotExists(
      name="ThreatReport",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("anomaly_score", models.FloatField()),
        ("top_location", models.CharField(default="Unknown", max_length=255)),
        ("location_weight", models.FloatField(default=0.0)),
        ("suspicious_ratio", models.FloatField(default=0.0)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "user",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="threat_reports",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "db_table": "threat_reports",
        "ordering": ["-created_at"],
      },
    ),
  ]
