# Generated by Django 5.2.15 on 2026-06-21 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("ml", "0003_threatreport"),
    ("monitor", "0022_create_tenant_0"),
  ]

  operations = [
    migrations.RemoveField(
      model_name="threatreport",
      name="user",
    ),
    migrations.RemoveField(
      model_name="trainingrun",
      name="status_page",
    ),
    migrations.AddField(
      model_name="threatreport",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="threat_reports",
        to="monitor.tenant",
      ),
    ),
    migrations.AddField(
      model_name="trainingrun",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="training_runs",
        to="monitor.tenant",
      ),
    ),
  ]
