# Generated by Django 5.2.15 on 2026-06-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("ml", "0004_remove_threatreport_user_and_more"),
    ("monitor", "0029_threatintelligence_threat_inte_ip_addr_03311d_idx_and_more"),
  ]

  operations = [
    migrations.AddIndex(
      model_name="threatreport",
      index=models.Index(fields=["created_at"], name="threat_repo_created_04515e_idx"),
    ),
    migrations.AddIndex(
      model_name="trainingrun",
      index=models.Index(fields=["created_at"], name="training_ru_created_2d8451_idx"),
    ),
  ]
