# Generated by Django 6.0.3 on 2026-06-07 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
        ('monitor', '0003_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrun',
            name='status_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='monitor.statuspage'),
        ),
    ]
