#!/usr/bin/env node
/**
 * Sync Lucide SVG paths into viking-ui (build-time only — zero runtime dependency).
 * Run: node scripts/sync_lucide_icons.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as lucide from 'lucide';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '../packages/viking-ui/src/core/lucide-paths.generated.ts');

/** Viking registry key → Lucide PascalCase export. */
const LUCIDE_MAP = {
  check: 'Check',
  x: 'X',
  plus: 'Plus',
  minus: 'Minus',
  'chevron-down': 'ChevronDown',
  'chevron-up': 'ChevronUp',
  'chevron-left': 'ChevronLeft',
  'chevron-right': 'ChevronRight',
  'arrow-right': 'ArrowRight',
  'arrow-left': 'ArrowLeft',
  'arrow-up-right': 'ArrowUpRight',
  search: 'Search',
  calendar: 'Calendar',
  clock: 'Clock',
  user: 'User',
  settings: 'Settings',
  info: 'Info',
  'alert-triangle': 'TriangleAlert',
  'alert-circle': 'CircleAlert',
  'check-circle': 'CircleCheck',
  bell: 'Bell',
  star: 'Star',
  heart: 'Heart',
  trash: 'Trash2',
  pencil: 'Pencil',
  copy: 'Copy',
  upload: 'Upload',
  download: 'Download',
  send: 'Send',
  paperclip: 'Paperclip',
  image: 'Image',
  file: 'File',
  folder: 'Folder',
  menu: 'Menu',
  'dots-horizontal': 'Ellipsis',
  'dots-vertical': 'EllipsisVertical',
  'grip-vertical': 'GripVertical',
  sun: 'Sun',
  moon: 'Moon',
  eye: 'Eye',
  'eye-off': 'EyeOff',
  bold: 'Bold',
  italic: 'Italic',
  underline: 'Underline',
  list: 'List',
  'list-ordered': 'ListOrdered',
  link: 'Link',
  home: 'House',
  mail: 'Mail',
  lock: 'Lock',
  globe: 'Globe',
  loader: 'LoaderCircle',
  sparkle: 'Sparkles',
  external: 'ExternalLink',
  filter: 'Filter',
  terminal: 'Terminal',
  refresh: 'RefreshCw',
  'log-out': 'LogOut',
  shield: 'Shield',
  'bar-chart': 'ChartColumn',
  phone: 'Phone',
  'trending-up': 'TrendingUp',
  fingerprint: 'Fingerprint',
  'user-shield': 'ShieldUser',
  chip: 'Cpu',
  brain: 'Brain',
  bolt: 'Zap',
  cloud: 'Cloud',
  server: 'Server',
  network: 'Network',
  speed: 'Gauge',
  rocket: 'Rocket',
  key: 'KeyRound',
  'log-in': 'LogIn',
  policy: 'ShieldCheck',
  bug: 'Bug',
  play: 'Play',
  building: 'Building',
  cookie: 'Cookie',
  'search-off': 'SearchX',
  insights: 'LineChart',
  ship: 'Ship',
};

/** Icons that render as filled dot grids (not stroke outlines). */
const FILLED_DOT_ICONS = new Set(['dots-horizontal', 'dots-vertical', 'grip-vertical']);

/** Icons always rendered filled regardless of variant. */
const ALWAYS_FILLED_ICONS = new Set(['play']);

const iconNodeToHtml = (nodes, vikingName) => {
  return nodes
    .map(([tag, attrs]) => {
      const merged = { ...attrs };
      if (FILLED_DOT_ICONS.has(vikingName) && tag === 'circle') {
        merged.fill = 'currentColor';
        merged.stroke = 'none';
      }
      if (ALWAYS_FILLED_ICONS.has(vikingName) && tag === 'path') {
        merged.fill = 'currentColor';
        merged.stroke = 'none';
      }
      const attrStr = Object.entries(merged)
        .map(([k, v]) => `${k}="${v}"`)
        .join(' ');
      return `<${tag} ${attrStr}/>`;
    })
    .join('');
};

const paths = {};
const missing = [];

for (const [vikingName, lucideName] of Object.entries(LUCIDE_MAP)) {
  const nodes = lucide[lucideName];
  if (!nodes) {
    missing.push(lucideName);
    continue;
  }
  paths[vikingName] = iconNodeToHtml(nodes, vikingName);
}

if (missing.length) {
  console.error('Missing Lucide exports:', missing.join(', '));
  process.exit(1);
}

const sortedKeys = Object.keys(paths).sort();
const body = sortedKeys.map(key => `  '${key}': '${paths[key].replace(/'/g, "\\'")}',`).join('\n');

const file = `/**
 * AUTO-GENERATED by scripts/sync_lucide_icons.mjs — do not edit by hand.
 * Lucide paths are inlined at build time; lucide is a devDependency only.
 * @see https://lucide.dev
 */
export const LUCIDE_ICON_PATHS = {
${body}
} as const;

export type LucideIconName = keyof typeof LUCIDE_ICON_PATHS;
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, file);
console.log(`Wrote ${sortedKeys.length} Lucide icons → ${path.relative(process.cwd(), OUT)}`);
