"""Canonical DEML use-case contracts (Python).

Narrative SoT: docs/use-cases/CANONICAL.md
Consumers must import from this package — do not re-declare DTOs.
"""

from deml_contracts.auth import (
  APIKeyGenerateIn,
  APIKeyGenerateOut,
  APIKeyOut,
  AuthUserResponse,
  DeleteAccountOut,
  DesktopAuthOut,
  DesktopSessionIn,
  HandoffGenerateIn,
  HandoffGenerateOut,
  HandoffVerifyIn,
  LogoutIn,
  SessionOut,
  SessionRegisterIn,
  SessionRegisterOut,
  SuccessSchema,
)
from deml_contracts.billing import (
  BillingErrorOut,
  BillingSyncOut,
  CheckoutSessionOut,
  SubscriptionMutateOut,
)
from deml_contracts.consent import (
  ConsentIn,
  ConsentRecordOut,
  NewsletterIn,
  NewsletterSubscribeOut,
)
from deml_contracts.env_schema import (
  LIVENESS_PATH,
  PAAS_FORJD_REQUIRED,
  READINESS_PATH,
  SUITE_URL_DEFAULTS,
  VERCEL_FRONTEND_REQUIRED,
  ConfigLayer,
  EnvVarSpec,
  RequiredOn,
)
from deml_contracts.errors import ErrorCode, ErrorEnvelope
from deml_contracts.factories import (
  make_billing_sync_out,
  make_consent_in,
  make_consent_record_out,
  make_newsletter_in,
  make_newsletter_out,
  make_sealed_batch_dict,
  make_sealed_event,
  make_sealed_event_dict,
  make_subscription_mutate_out,
)
from deml_contracts.ids import USE_CASE_IDS, UseCaseId
from deml_contracts.ingest import (
  ALLOWED_METADATA_KEYS,
  EVENT_TYPE_TO_FORJD,
  FORJD_TELEMETRY_WORKFLOW_ID,
  MAX_INGEST_BATCH_EVENTS,
  MAX_INGEST_BODY_BYTES,
  TELEMETRY_CONTENT_TYPE,
  TELEMETRY_WORKFLOW_ID,
  WORKFLOW_ID_TO_FORJD,
  EncryptedEnvelope,
  EncryptionOptions,
  SealedEvent,
  SealedEventBatch,
  rewrite_forjd_workflow_body,
  rewrite_forjd_workflow_query,
  sealed_batch_for_forjd,
  sealed_event_for_forjd,
)
from deml_contracts.live import LiveSseDegraded, LiveSseEnd, LiveSseProjections, LiveSseReady
from deml_contracts.playbooks import PlaybookActionAckIn, PlaybookActionRetryIn
from deml_contracts.ready import ReadyResponse

__all__ = [
  "ALLOWED_METADATA_KEYS",
  "APIKeyGenerateIn",
  "APIKeyGenerateOut",
  "APIKeyOut",
  "AuthUserResponse",
  "BillingErrorOut",
  "BillingSyncOut",
  "CheckoutSessionOut",
  "ConfigLayer",
  "ConsentIn",
  "ConsentRecordOut",
  "DeleteAccountOut",
  "DesktopAuthOut",
  "DesktopSessionIn",
  "EnvVarSpec",
  "EVENT_TYPE_TO_FORJD",
  "EncryptedEnvelope",
  "EncryptionOptions",
  "ErrorCode",
  "ErrorEnvelope",
  "FORJD_TELEMETRY_WORKFLOW_ID",
  "HandoffGenerateIn",
  "HandoffGenerateOut",
  "HandoffVerifyIn",
  "LIVENESS_PATH",
  "LiveSseDegraded",
  "LiveSseEnd",
  "LiveSseProjections",
  "LiveSseReady",
  "LogoutIn",
  "MAX_INGEST_BATCH_EVENTS",
  "MAX_INGEST_BODY_BYTES",
  "NewsletterIn",
  "NewsletterSubscribeOut",
  "PAAS_FORJD_REQUIRED",
  "PlaybookActionAckIn",
  "PlaybookActionRetryIn",
  "READINESS_PATH",
  "ReadyResponse",
  "RequiredOn",
  "SUITE_URL_DEFAULTS",
  "SealedEvent",
  "SealedEventBatch",
  "SessionOut",
  "SessionRegisterIn",
  "SessionRegisterOut",
  "SubscriptionMutateOut",
  "SuccessSchema",
  "TELEMETRY_CONTENT_TYPE",
  "TELEMETRY_WORKFLOW_ID",
  "USE_CASE_IDS",
  "UseCaseId",
  "VERCEL_FRONTEND_REQUIRED",
  "WORKFLOW_ID_TO_FORJD",
  "make_billing_sync_out",
  "make_consent_in",
  "make_consent_record_out",
  "make_newsletter_in",
  "make_newsletter_out",
  "make_sealed_batch_dict",
  "make_sealed_event",
  "make_sealed_event_dict",
  "make_subscription_mutate_out",
  "rewrite_forjd_workflow_body",
  "rewrite_forjd_workflow_query",
  "sealed_batch_for_forjd",
  "sealed_event_for_forjd",
]
