// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js';
import { configureBoneyard } from 'boneyard-js/angular';

import _isolated_status_page from './isolated-status-page.bones.json';
import _announcements from './announcements.bones.json';
import _status_pages from './status-pages.bones.json';

configureBoneyard({
  animate: 'shimmer',
  color: '#e1e6e2',
  darkColor: '#182821',
  stagger: true,
  transition: true,
});

registerBones({
  'isolated-status-page': _isolated_status_page,
  announcements: _announcements,
  'status-pages': _status_pages,
});
