# Generated by Django 6.0.3 on 2026-06-02 23:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('last_tested', models.DateTimeField(auto_now=True)),
                ('status_code', models.IntegerField()),
                ('response_time', models.DurationField()),
                ('ip_address', models.GenericIPAddressField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'endpoints',
            },
        ),
    ]
