# Generated by Django 6.0.3 on 2026-06-07 04:27

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0002_alter_endpoints_ip_address_statuspage_and_more"),
  ]

  operations = [
    migrations.CreateModel(
      name="Incident",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("title", models.CharField(max_length=255)),
        ("message", models.TextField()),
        (
          "status",
          models.CharField(
            choices=[
              ("Investigating", "Investigating"),
              ("Identified", "Identified"),
              ("Monitoring", "Monitoring"),
              ("Resolved", "Resolved"),
            ],
            default="Investigating",
            max_length=50,
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "status_page",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="incidents",
            to="monitor.statuspage",
          ),
        ),
      ],
      options={
        "db_table": "incidents",
        "ordering": ["-created_at"],
      },
    ),
  ]
