# Generated by Django 6.0.3 on 2026-06-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0004_bugreport_cookieconsent"),
  ]

  operations = [
    migrations.AddField(
      model_name="statuspage",
      name="is_published",
      field=models.BooleanField(default=False),
    ),
  ]
