# Generated by Django 6.0.3 on 2026-06-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0006_endpoints_endpoints_url_1d9dde_idx_and_more"),
  ]

  operations = [
    migrations.AddField(
      model_name="statuspage",
      name="google_analytics_id",
      field=models.CharField(blank=True, max_length=100, null=True),
    ),
    migrations.AddField(
      model_name="statuspage",
      name="microsoft_clarity_id",
      field=models.CharField(blank=True, max_length=100, null=True),
    ),
  ]
