# Generated by Django 6.0.3 on 2026-06-13 05:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0007_statuspage_google_analytics_id_and_more"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="AnalyticsIntegration",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("provider", models.CharField(max_length=50)),
        ("credentials", models.JSONField(blank=True, default=dict)),
        ("active", models.BooleanField(default=True)),
        ("last_sync", models.DateTimeField(blank=True, null=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "user",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="analytics_integrations",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "db_table": "analytics_integrations",
        "unique_together": {("user", "provider")},
      },
    ),
  ]
