# Generated by Django 6.0.3 on 2026-06-13 18:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0009_rename_model_to_ml"),
  ]

  operations = [
    migrations.CreateModel(
      name="NewsletterSubscription",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("email", models.EmailField(max_length=254, unique=True)),
        ("subscribed_at", models.DateTimeField(auto_now_add=True)),
        ("consent_accepted", models.BooleanField(default=False)),
      ],
      options={
        "db_table": "newsletter_subscriptions",
        "ordering": ["-subscribed_at"],
      },
    ),
  ]
