# Generated by Django 6.0.3 on 2026-06-13 20:38

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0010_newslettersubscription"),
  ]

  operations = [
    migrations.CreateModel(
      name="DataEncryptionKey",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("encrypted_dek", models.TextField()),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("is_active", models.BooleanField(default=True)),
      ],
      options={
        "db_table": "data_encryption_keys",
        "ordering": ["-created_at"],
      },
    ),
  ]
