# Generated by Django 6.0.3 on 2026-06-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0011_dataencryptionkey"),
  ]

  operations = [
    migrations.AddField(
      model_name="statuspage",
      name="cloudflare_analytics_id",
      field=models.CharField(blank=True, max_length=100, null=True),
    ),
  ]
