# Generated by Django 6.0.5 on 2026-06-15 02:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0015_userprofile"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="ThreatIntelligence",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("source", models.CharField(max_length=255)),
        ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
        ("location", models.CharField(blank=True, max_length=255, null=True)),
        ("abuse_confidence_score", models.IntegerField(default=0)),
        ("otx_pulses", models.IntegerField(default=0)),
        ("is_malicious", models.BooleanField(default=False)),
        ("active_users", models.IntegerField(blank=True, null=True)),
        ("suspicious_requests", models.IntegerField(blank=True, null=True)),
        ("raw_payload", models.JSONField(blank=True, null=True)),
        ("timestamp", models.DateTimeField(auto_now_add=True)),
        (
          "user",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name="threat_intelligence",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "db_table": "threat_intelligence",
        "ordering": ["-timestamp"],
      },
    ),
  ]
