# Generated by Django 5.2.15 on 2026-06-18 23:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0016_threatintelligence"),
  ]

  operations = [
    migrations.CreateModel(
      name="AggregatedAnalytics",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        (
          "timestamp",
          models.DateTimeField(db_index=True, help_text="The start time of the aggregation bucket"),
        ),
        (
          "bucket_size",
          models.CharField(default="1h", help_text="e.g., '1h', '1d'", max_length=50),
        ),
        ("total_requests", models.BigIntegerField(default=0)),
        ("avg_latency_ms", models.FloatField(default=0.0)),
        ("p99_latency_ms", models.FloatField(default=0.0)),
        ("error_rate_percent", models.FloatField(default=0.0)),
        ("threats_detected", models.IntegerField(default=0)),
        ("active_incidents", models.IntegerField(default=0)),
        ("unique_visitors", models.IntegerField(default=0)),
        ("cookie_consents_analytical", models.IntegerField(default=0)),
        ("cookie_consents_marketing", models.IntegerField(default=0)),
        ("widget_interactions", models.IntegerField(default=0)),
        ("metadata", models.JSONField(blank=True, default=dict)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
      ],
      options={
        "db_table": "aggregated_analytics",
        "ordering": ["-timestamp"],
        "unique_together": {("timestamp", "bucket_size")},
      },
    ),
  ]
