# Generated by Django 5.2.15 on 2026-06-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):
  """
  django-migration-linter: ignore
  """

  dependencies = [
    ("monitor", "0017_aggregatedanalytics"),
  ]

  operations = [
    migrations.AddField(
      model_name="endpoints",
      name="asn",
      field=models.CharField(blank=True, max_length=255, null=True),
    ),
    migrations.AddField(
      model_name="endpoints",
      name="browser_name",
      field=models.CharField(blank=True, max_length=50, null=True),
    ),
    migrations.AddField(
      model_name="endpoints",
      name="device_type",
      field=models.CharField(blank=True, max_length=50, null=True),
    ),
    migrations.AddField(
      model_name="endpoints",
      name="is_bot",
      field=models.BooleanField(blank=True, default=False, null=True),
    ),
    migrations.AddField(
      model_name="endpoints",
      name="isp",
      field=models.CharField(blank=True, max_length=255, null=True),
    ),
    migrations.AddField(
      model_name="endpoints",
      name="location",
      field=models.CharField(blank=True, max_length=255, null=True),
    ),
    migrations.AddField(
      model_name="endpoints",
      name="os_name",
      field=models.CharField(blank=True, max_length=50, null=True),
    ),
  ]
