# Generated by Django 5.2.15 on 2026-06-20 20:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0018_endpoints_traffic_enrichment"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="APIKey",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("name", models.CharField(max_length=255)),
        ("prefix", models.CharField(max_length=8, unique=True)),
        ("key_hash", models.CharField(max_length=128)),
        ("is_active", models.BooleanField(default=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "user",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="api_keys",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
    ),
  ]
