# Generated by Django 5.2.15 on 2026-06-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0019_apikey"),
  ]

  operations = [
    migrations.AddField(
      model_name="endpoints",
      name="telemetry_context",
      field=models.JSONField(blank=True, null=True),
    ),
  ]
