# Generated by Django 5.2.15 on 2026-06-21 00:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0020_endpoints_telemetry_context"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="Tenant",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("name", models.CharField(max_length=255)),
        ("slug", models.SlugField(max_length=255, unique=True)),
        ("target_url", models.URLField(blank=True, null=True)),
        ("is_platform_tenant", models.BooleanField(default=False)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
      ],
      options={
        "db_table": "tenants",
      },
    ),
    migrations.AddField(
      model_name="aggregatedanalytics",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="aggregated_analytics",
        to="monitor.tenant",
      ),
    ),
    migrations.AddField(
      model_name="bugreport",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="bug_reports",
        to="monitor.tenant",
      ),
    ),
    migrations.AddField(
      model_name="cookieconsent",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="cookie_consents",
        to="monitor.tenant",
      ),
    ),
    migrations.AddField(
      model_name="endpoints",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="endpoints",
        to="monitor.tenant",
      ),
    ),
    migrations.AddField(
      model_name="incident",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="incidents",
        to="monitor.tenant",
      ),
    ),
    migrations.AddField(
      model_name="statuspage",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="status_pages",
        to="monitor.tenant",
      ),
    ),
    migrations.AddField(
      model_name="threatintelligence",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="threat_intel",
        to="monitor.tenant",
      ),
    ),
    migrations.AddField(
      model_name="vulnerability",
      name="tenant",
      field=models.ForeignKey(
        blank=True,
        null=True,
        on_delete=django.db.models.deletion.CASCADE,
        related_name="vulnerabilities",
        to="monitor.tenant",
      ),
    ),
    migrations.CreateModel(
      name="TenantMembership",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        (
          "role",
          models.CharField(
            choices=[("Owner", "Owner"), ("Admin", "Admin"), ("Viewer", "Viewer")],
            default="Viewer",
            max_length=50,
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "tenant",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, related_name="members", to="monitor.tenant"
          ),
        ),
        (
          "user",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="tenant_memberships",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "db_table": "tenant_memberships",
        "unique_together": {("user", "tenant")},
      },
    ),
  ]
