# Generated by Django 5.2.15 on 2026-06-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0022_create_tenant_0"),
  ]

  operations = [
    migrations.AddField(
      model_name="tenant",
      name="stripe_customer_id",
      field=models.CharField(blank=True, max_length=255, null=True),
    ),
    migrations.AddField(
      model_name="tenant",
      name="stripe_subscription_id",
      field=models.CharField(blank=True, max_length=255, null=True),
    ),
    migrations.AddField(
      model_name="tenant",
      name="subscription_active",
      field=models.BooleanField(default=True),
    ),
    migrations.AddField(
      model_name="tenant",
      name="tier",
      field=models.CharField(
        choices=[("Standard", "Standard"), ("Pro", "Pro")], default="Standard", max_length=50
      ),
    ),
  ]
