# Generated by Django 5.2.15 on 2026-06-23 02:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0023_tenant_stripe_customer_id_and_more"),
  ]

  operations = [
    migrations.CreateModel(
      name="ValidatedSite",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("domain", models.CharField(max_length=255)),
        ("is_verified", models.BooleanField(default=True)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "tenant",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="validated_sites",
            to="monitor.tenant",
          ),
        ),
      ],
      options={
        "db_table": "validated_sites",
        "unique_together": {("tenant", "domain")},
      },
    ),
  ]
