# Generated by Django 5.2.15 on 2026-06-23 02:56

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0024_validatedsite"),
  ]

  operations = [
    migrations.AlterUniqueTogether(
      name="aggregatedanalytics",
      unique_together={("tenant", "timestamp", "bucket_size")},
    ),
  ]
