# Generated by Django 5.2.15 on 2026-06-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0026_asset_vulnerability_asset"),
  ]

  operations = [
    migrations.AddField(
      model_name="tenant",
      name="subscription_current_period_end",
      field=models.DateTimeField(blank=True, null=True),
    ),
  ]
