# Generated by Django 4.2.16

from django.db import migrations


def remove_platform_tenant_memberships(apps, schema_editor):
  TenantMembership = apps.get_model("monitor", "TenantMembership")
  Tenant = apps.get_model("monitor", "Tenant")

  # Get the platform tenant
  platform_tenant = Tenant.objects.filter(is_platform_tenant=True).first()
  if platform_tenant:
    # Delete all memberships associated with the platform tenant
    TenantMembership.objects.filter(tenant=platform_tenant).delete()


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0027_tenant_subscription_current_period_end"),
  ]

  operations = [
    migrations.RunPython(
      remove_platform_tenant_memberships, reverse_code=migrations.RunPython.noop
    ),
  ]
