# Generated by Django 5.2.15 on 2026-06-26 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0028_remove_platform_tenant_memberships"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AddIndex(
      model_name="threatintelligence",
      index=models.Index(fields=["ip_address"], name="threat_inte_ip_addr_03311d_idx"),
    ),
    migrations.AddIndex(
      model_name="threatintelligence",
      index=models.Index(fields=["source"], name="threat_inte_source_0387cf_idx"),
    ),
    migrations.AddConstraint(
      model_name="threatintelligence",
      constraint=models.UniqueConstraint(
        fields=("user", "source", "ip_address", "location"),
        name="unique_threat_intel_per_user_source_ip_location",
      ),
    ),
  ]
