# Generated by Django 5.2.15 on 2026-06-26 00:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0029_threatintelligence_threat_inte_ip_addr_03311d_idx_and_more"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="IncidentCase",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("title", models.CharField(max_length=255)),
        ("description", models.TextField(blank=True, null=True)),
        (
          "status",
          models.CharField(
            choices=[
              ("Open", "Open"),
              ("Investigating", "Investigating"),
              ("Mitigated", "Mitigated"),
              ("Resolved", "Resolved"),
              ("False Positive", "False Positive"),
            ],
            default="Open",
            max_length=50,
          ),
        ),
        (
          "severity",
          models.CharField(
            choices=[
              ("Low", "Low"),
              ("Medium", "Medium"),
              ("High", "High"),
              ("Critical", "Critical"),
            ],
            default="Medium",
            max_length=50,
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "assigned_to",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.SET_NULL,
            related_name="assigned_cases",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        (
          "related_threats",
          models.ManyToManyField(
            blank=True, related_name="incident_cases", to="monitor.threatintelligence"
          ),
        ),
        (
          "tenant",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="incident_cases",
            to="monitor.tenant",
          ),
        ),
      ],
      options={
        "db_table": "incident_cases",
        "ordering": ["-created_at"],
      },
    ),
    migrations.CreateModel(
      name="Playbook",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("name", models.CharField(max_length=255)),
        ("description", models.TextField(blank=True, null=True)),
        ("is_active", models.BooleanField(default=True)),
        (
          "trigger_conditions",
          models.JSONField(
            default=dict, help_text="JSON representation of conditions to trigger this playbook"
          ),
        ),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("updated_at", models.DateTimeField(auto_now=True)),
        (
          "tenant",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="playbooks",
            to="monitor.tenant",
          ),
        ),
      ],
      options={
        "db_table": "playbooks",
      },
    ),
    migrations.CreateModel(
      name="PlaybookAction",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        (
          "action_type",
          models.CharField(
            choices=[
              ("Webhook", "Webhook"),
              ("EmailAlert", "Email Alert"),
              ("BlockIP", "Block IP"),
              ("RevokeAPIKey", "Revoke API Key"),
            ],
            max_length=50,
          ),
        ),
        (
          "configuration",
          models.JSONField(
            default=dict, help_text="Configuration for the action (e.g., URL for webhook)"
          ),
        ),
        ("order", models.IntegerField(default=0, help_text="Order of execution")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        (
          "playbook",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="actions",
            to="monitor.playbook",
          ),
        ),
      ],
      options={
        "db_table": "playbook_actions",
        "ordering": ["order"],
      },
    ),
  ]
