# Generated by Django 5.2.15 on 2026-06-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0030_incidentcase_playbook_playbookaction"),
  ]

  operations = [
    migrations.AddField(
      model_name="userprofile",
      name="linked_emails",
      field=models.JSONField(blank=True, default=list, null=True),
    ),
  ]
