# Generated by Django 5.2.15 on 2026-06-27 22:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0031_userprofile_linked_emails"),
  ]

  operations = [
    migrations.CreateModel(
      name="OutboxEvent",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("topic", models.CharField(max_length=100)),
        ("key", models.CharField(blank=True, max_length=255, null=True)),
        ("payload", models.JSONField()),
        ("headers", models.JSONField(blank=True, default=dict)),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("published_at", models.DateTimeField(blank=True, null=True)),
        ("attempts", models.IntegerField(default=0)),
        ("last_error", models.TextField(blank=True, null=True)),
        ("is_published", models.BooleanField(default=False)),
      ],
      options={
        "ordering": ["created_at"],
        "indexes": [
          models.Index(
            fields=["is_published", "created_at"], name="monitor_out_is_publ_0e682d_idx"
          ),
          models.Index(fields=["topic"], name="monitor_out_topic_d92b48_idx"),
        ],
      },
    ),
  ]
