# Generated by Django 5.2.15 on 2026-06-28 23:45
# Refactored to use AddIndex — Antigravity - Claude Opus 4.6
# AlterField triggers a table rebuild on SQLite; AddIndex is non-destructive.

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0035_syntheticmonitor"),
  ]

  operations = [
    migrations.AddIndex(
      model_name="auditlog",
      index=models.Index(fields=["action"], name="audit_action_idx"),
    ),
    migrations.AddIndex(
      model_name="vulnerability",
      index=models.Index(fields=["severity"], name="vuln_severity_idx"),
    ),
    migrations.AddIndex(
      model_name="vulnerability",
      index=models.Index(fields=["status"], name="vuln_status_idx"),
    ),
  ]
