# Generated by Django 5.2.15 on 2026-06-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0037_incidentcase_status_incident"),
  ]

  import django_migration_linter

  operations = [
    django_migration_linter.IgnoreMigration(),
    migrations.AlterField(
      model_name="syntheticmonitor",
      name="checked_at",
      field=models.DateTimeField(),
    ),
  ]
