# Generated by Django 5.2.15 on 2026-06-30 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0038_syntheticmonitor_checked_at_explicit"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.AddIndex(
      model_name="auditlog",
      index=models.Index(fields=["timestamp"], name="audit_logs_timesta_423be6_idx"),
    ),
    migrations.AddIndex(
      model_name="bugreport",
      index=models.Index(fields=["created_at"], name="bug_reports_created_c948ac_idx"),
    ),
    migrations.AddIndex(
      model_name="cookieconsent",
      index=models.Index(fields=["created_at"], name="cookie_cons_created_f347bb_idx"),
    ),
    migrations.AddIndex(
      model_name="endpoints",
      index=models.Index(
        fields=["user", "is_platform", "last_tested"], name="endpoints_user_id_ebf0ca_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="incident",
      index=models.Index(fields=["created_at"], name="incidents_created_bc994b_idx"),
    ),
    migrations.AddIndex(
      model_name="incidentcase",
      index=models.Index(fields=["created_at"], name="incident_ca_created_7a7b19_idx"),
    ),
    migrations.AddIndex(
      model_name="incidentcase",
      index=models.Index(fields=["status"], name="incident_ca_status_33d183_idx"),
    ),
    migrations.AddIndex(
      model_name="threatintelligence",
      index=models.Index(fields=["timestamp"], name="threat_inte_timesta_e5bad3_idx"),
    ),
    migrations.AddIndex(
      model_name="threatintelligence",
      index=models.Index(
        fields=["user", "is_platform", "timestamp"], name="threat_inte_user_id_d96eff_idx"
      ),
    ),
    migrations.AddIndex(
      model_name="vulnerability",
      index=models.Index(fields=["created_at"], name="vulnerabili_created_e60b65_idx"),
    ),
  ]
