# Generated by Django 5.2.15 on 2026-07-11 01:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0042_alter_outboxevent_available_at"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="ExportJob",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("account_id", models.UUIDField(db_index=True)),
        (
          "kind",
          models.CharField(
            choices=[
              ("analytics", "Analytics"),
              ("threat", "Threat intelligence"),
              ("lighthouse", "Lighthouse"),
              ("vulnerabilities", "Vulnerabilities"),
              ("custom", "Custom"),
            ],
            default="analytics",
            max_length=32,
          ),
        ),
        (
          "format",
          models.CharField(
            choices=[("csv", "CSV"), ("json", "JSON"), ("parquet", "Parquet"), ("pdf", "PDF")],
            default="csv",
            max_length=16,
          ),
        ),
        ("params", models.JSONField(blank=True, default=dict)),
        (
          "status",
          models.CharField(
            choices=[
              ("queued", "Queued"),
              ("running", "Running"),
              ("ready", "Ready"),
              ("failed", "Failed"),
              ("expired", "Expired"),
            ],
            default="queued",
            max_length=16,
          ),
        ),
        ("storage_uri", models.CharField(blank=True, default="", max_length=1024)),
        ("object_key", models.CharField(blank=True, default="", max_length=1024)),
        ("content_type", models.CharField(blank=True, default="", max_length=128)),
        ("byte_size", models.BigIntegerField(default=0)),
        ("checksum_sha256", models.CharField(blank=True, default="", max_length=64)),
        ("error", models.TextField(blank=True, default="")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("started_at", models.DateTimeField(blank=True, null=True)),
        ("completed_at", models.DateTimeField(blank=True, null=True)),
        ("expires_at", models.DateTimeField(blank=True, null=True)),
        (
          "user",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="export_jobs",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "db_table": "export_jobs",
        "ordering": ["-created_at"],
        "indexes": [
          models.Index(
            fields=["user", "status", "-created_at"], name="export_jobs_user_status_idx"
          ),
          models.Index(fields=["account_id", "-created_at"], name="export_jobs_account_idx"),
          models.Index(fields=["status", "expires_at"], name="export_jobs_expiry_idx"),
        ],
      },
    ),
  ]
