# Generated by Django 5.2.15 on 2026-07-12 17:29

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0045_honeypot_benchmark_models"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="SearchQuery",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("is_platform", models.BooleanField(default=False)),
        ("query_text", models.TextField()),
        ("threat_score", models.FloatField(default=0.0)),
        ("source", models.CharField(default="algolia", max_length=50)),
        ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
        ("user_agent", models.TextField(blank=True, null=True)),
        ("timestamp", models.DateTimeField(auto_now_add=True)),
        (
          "user",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name="search_queries",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
      ],
      options={
        "db_table": "search_queries",
        "ordering": ["-timestamp"],
        "indexes": [
          models.Index(fields=["timestamp"], name="search_quer_timesta_7fd56f_idx"),
          models.Index(fields=["threat_score"], name="search_quer_threat__e7f8e2_idx"),
          models.Index(
            fields=["user", "is_platform", "timestamp"], name="search_quer_user_id_3d3dc5_idx"
          ),
        ],
      },
    ),
  ]
