# Generated by Django 5.2.15 on 2026-07-14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("monitor", "0046_searchquery"),
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name="WebTechnologyObservation",
      fields=[
        (
          "id",
          models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        ("account_id", models.UUIDField(db_index=True)),
        ("is_platform", models.BooleanField(db_index=True, default=False)),
        (
          "source",
          models.CharField(
            choices=[("firecrawl", "Firecrawl"), ("wappalyzer", "Wappalyzer")],
            max_length=32,
          ),
        ),
        ("source_url", models.URLField(max_length=2048)),
        ("technology_name", models.CharField(max_length=255)),
        ("normalized_name", models.CharField(max_length=255)),
        ("version", models.CharField(blank=True, default="", max_length=128)),
        ("confidence", models.FloatField(default=0.0)),
        ("evidence", models.JSONField(blank=True, default=list)),
        ("cpe_2_3", models.CharField(blank=True, default="", max_length=1024)),
        ("cve_ids", models.JSONField(blank=True, default=list)),
        ("first_seen_at", models.DateTimeField(auto_now_add=True)),
        ("last_seen_at", models.DateTimeField(auto_now=True)),
        (
          "user",
          models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.CASCADE,
            related_name="web_technology_observations",
            to=settings.AUTH_USER_MODEL,
          ),
        ),
        (
          "validated_site",
          models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE,
            related_name="technology_observations",
            to="monitor.validatedsite",
          ),
        ),
      ],
      options={
        "db_table": "web_technology_observations",
        "ordering": ["normalized_name", "version"],
        "indexes": [
          models.Index(fields=["account_id", "-last_seen_at"], name="web_tech_account_seen_idx"),
          models.Index(
            fields=["user", "is_platform", "-last_seen_at"], name="web_tech_scope_seen_idx"
          ),
          models.Index(fields=["cpe_2_3"], name="web_tech_cpe_idx"),
        ],
        "constraints": [
          models.UniqueConstraint(
            fields=("validated_site", "source", "normalized_name", "version"),
            name="unique_site_technology_version",
          )
        ],
      },
    ),
  ]
