# Generated by Django 5.2.15 on 2026-07-15

from typing import Any

from django.db import migrations, models


def enforce_attempts_not_null(apps: Any, schema_editor: Any) -> None:
  ExportJob = apps.get_model("monitor", "ExportJob")
  ExportJob.objects.filter(attempts__isnull=True).update(attempts=0)
  if schema_editor.connection.vendor != "postgresql":
    return
  schema_editor.execute(
    'ALTER TABLE "export_jobs" ADD CONSTRAINT "export_jobs_attempts_not_null" '
    'CHECK ("attempts" IS NOT NULL) NOT VALID'
  )
  schema_editor.execute(
    'ALTER TABLE "export_jobs" VALIDATE CONSTRAINT "export_jobs_attempts_not_null"'
  )
  schema_editor.execute('ALTER TABLE "export_jobs" ALTER COLUMN "attempts" SET NOT NULL')
  schema_editor.execute('ALTER TABLE "export_jobs" DROP CONSTRAINT "export_jobs_attempts_not_null"')


def relax_attempts_not_null(apps: Any, schema_editor: Any) -> None:
  if schema_editor.connection.vendor == "postgresql":
    schema_editor.execute('ALTER TABLE "export_jobs" ALTER COLUMN "attempts" DROP NOT NULL')


class Migration(migrations.Migration):
  """Add retry state without rewriting or blocking the existing export table.

  SQLite test databases retain a nullable physical column; production PostgreSQL
  receives the validated ``NOT NULL`` invariant before migration state advances.
  """

  dependencies = [
    ("monitor", "0048_status_page_uptime_daily"),
  ]

  operations = [
    migrations.AddField(
      model_name="exportjob",
      name="attempts",
      field=models.PositiveSmallIntegerField(null=True),
    ),
    migrations.RunPython(
      enforce_attempts_not_null,
      reverse_code=relax_attempts_not_null,
    ),
    migrations.SeparateDatabaseAndState(
      state_operations=[
        migrations.AlterField(
          model_name="exportjob",
          name="attempts",
          field=models.PositiveSmallIntegerField(default=0),
        ),
      ],
    ),
    migrations.AddField(
      model_name="exportjob",
      name="next_attempt_at",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddIndex(
      model_name="exportjob",
      index=models.Index(fields=["status", "next_attempt_at"], name="export_jobs_retry_idx"),
    ),
  ]
