#!/usr/bin/env node
/**
 * Build Blue Notes from markdown → generated TS + RSS.
 * Source: src/content/blue-notes/*.md
 * Output: src/app/data/blue-notes.generated.ts, public/blog/rss.xml
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const root = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const notesDir = join(root, 'src/content/blue-notes');
const outTs = join(root, 'src/app/data/blue-notes.generated.ts');
const outRss = join(root, 'public/blog/rss.xml');
const SITE = 'https://deml.app';
const VISUALS = ['gold', 'olive', 'red'];

// --- Frontmatter / slug helpers ---
function parseFrontmatter(raw) {
	const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
	if (!match) return { data: {}, body: raw };
	const data = {};
	for (const line of match[1].split('\n')) {
		const idx = line.indexOf(':');
		if (idx === -1) continue;
		const key = line.slice(0, idx).trim();
		let value = line.slice(idx + 1).trim();
		if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
		if (key === 'categories') {
			data.categories = [];
			continue;
		}
		if (key === 'featured' || key === 'draft') {
			data[key] = value === 'true';
			continue;
		}
		data[key] = value;
	}
	// YAML list items under categories
	const catBlock = match[1].match(/categories:\s*\n((?:\s+-\s+.+\n?)*)/);
	if (catBlock) {
		data.categories = catBlock[1]
			.split('\n')
			.map((l) => l.replace(/^\s*-\s*/, '').trim())
			.filter(Boolean);
	}
	return { data, body: match[2] };
}

function slugify(text) {
	return String(text)
		.toLowerCase()
		.replace(/<[^>]+>/g, '')
		.replace(/&[a-z]+;/g, '')
		.replace(/[^\w\s-]/g, '')
		.trim()
		.replace(/\s+/g, '-');
}

function formatLongDate(iso) {
	const d = new Date(`${iso}T00:00:00.000Z`);
	return new Intl.DateTimeFormat('en-US', { dateStyle: 'long', timeZone: 'UTC' }).format(d);
}

function formatMeta(iso, categories) {
	const d = new Date(`${iso}T00:00:00.000Z`);
	const short = new Intl.DateTimeFormat('en-US', {
		month: 'short',
		year: 'numeric',
		timeZone: 'UTC',
	}).format(d);
	const cat = categories?.[0] ?? 'Notes';
	return `${short} · ${cat}`;
}

function escapeHtml(s) {
	return String(s)
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}

function escapeTs(s) {
	return JSON.stringify(s);
}

// --- Heading IDs for TOC ---
marked.use({
	hooks: {
		preprocess(src) {
			return src;
		},
	},
	renderer: {
		heading({ tokens, depth, text }) {
			const label = this.parser.parseInline(tokens);
			const id = slugify(text);
			return `<h${depth} id="${id}">${label}</h${depth}>\n`;
		},
	},
});

// --- Load notes ---
const files = readdirSync(notesDir)
	.filter((f) => f.endsWith('.md'))
	.sort();

const notes = [];
for (const file of files) {
	const raw = readFileSync(join(notesDir, file), 'utf8');
	const { data, body } = parseFrontmatter(raw);
	if (data.draft) continue;

	const slug = basename(file, '.md');
	const html = marked.parse(body, { async: false });
	const headings = [];
	const headingRe = /<h2 id="([^"]+)">([\s\S]*?)<\/h2>/g;
	let m;
	while ((m = headingRe.exec(html)) !== null) {
		headings.push({
			slug: m[1],
			text: m[2].replace(/<[^>]+>/g, '').trim(),
		});
	}

	const publishedAt = String(data.publishedAt ?? '1970-01-01');
	const categories = Array.isArray(data.categories) ? data.categories : [];

	notes.push({
		slug,
		title: data.title ?? slug,
		summary: data.summary ?? '',
		note: data.note ?? 'Platform Note',
		publishedAt,
		updatedAt: data.updatedAt ?? null,
		categories,
		featured: Boolean(data.featured),
		meta: formatMeta(publishedAt, categories),
		publishedLabel: formatLongDate(publishedAt),
		visual: VISUALS[notes.length % VISUALS.length],
		html,
		headings,
	});
}

notes.sort((a, b) => {
	const byDate = b.publishedAt.localeCompare(a.publishedAt);
	if (byDate !== 0) return byDate;
	return b.note.localeCompare(a.note, 'en', { numeric: true });
});

// Re-assign visuals after sort for stable newest-first palette
notes.forEach((n, i) => {
	n.visual = VISUALS[i % VISUALS.length];
});

const ts = `/* AUTO-GENERATED by scripts/generate_blue_notes.mjs — do not edit */
import type { BlueNote } from './blue-notes';

export const BLUE_NOTES: readonly BlueNote[] = [
${notes
	.map(
		(n) => `  {
    slug: ${escapeTs(n.slug)},
    title: ${escapeTs(n.title)},
    summary: ${escapeTs(n.summary)},
    note: ${escapeTs(n.note)},
    publishedAt: ${escapeTs(n.publishedAt)},
    updatedAt: ${n.updatedAt ? escapeTs(n.updatedAt) : 'null'},
    categories: ${escapeTs(n.categories)},
    featured: ${n.featured},
    meta: ${escapeTs(n.meta)},
    publishedLabel: ${escapeTs(n.publishedLabel)},
    visual: ${escapeTs(n.visual)},
    html: ${escapeTs(n.html)},
    headings: ${escapeTs(n.headings)},
  }`,
	)
	.join(',\n')}
] as const;
`;

writeFileSync(outTs, ts);

mkdirSync(join(root, 'public/blog'), { recursive: true });
const rssItems = notes
	.map(
		(n) => `    <item>
      <title>${escapeHtml(n.title)}</title>
      <link>${SITE}/blog/${n.slug}</link>
      <guid isPermaLink="true">${SITE}/blog/${n.slug}</guid>
      <pubDate>${new Date(`${n.publishedAt}T12:00:00.000Z`).toUTCString()}</pubDate>
      <description>${escapeHtml(n.summary)}</description>
      <category>${escapeHtml(n.note)}</category>
    </item>`,
	)
	.join('\n');

writeFileSync(
	outRss,
	`<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>DEML Blue Notes</title>
    <link>${SITE}/blog</link>
    <description>Field log of DEML platform releases, architecture, and operator capabilities.</description>
    <language>en-us</language>
${rssItems}
  </channel>
</rss>
`,
);

console.log(`generate_blue_notes: ${notes.length} notes → ${outTs}`);
