import json

from utils.kafka import create_kafka_producer


async def send_issue_to_redpanda(topic: str, issue_report: str, bug_report_id: str | None = None):
  """
  Sends a formatted issue report to a specific Redpanda topic.

  Args:
      topic: The topic name (e.g., 'user-issues').
      issue_report: The stringified report generated by the agent.
      bug_report_id: The UUID/ID of the corresponding bug report in the database.
  """
  payload = {"event_type": "user_issue", "report": issue_report, "bug_report_id": bug_report_id}
  producer = create_kafka_producer()
  await producer.start()
  try:
    value = json.dumps(payload).encode("utf-8")
    await producer.send_and_wait(topic, value)
  finally:
    await producer.stop()
  return f"Successfully sent issue report to topic '{topic}'"
