import json

from utils.kafka import create_kafka_producer, send_kafka_value


async def send_issue_to_redpanda(topic: str, issue_report: str, bug_report_id: str | None = None):
  """
  Sends a formatted issue report to a specific Redpanda topic.

  Args:
      topic: The topic name (e.g., 'user-issues').
      issue_report: The stringified report generated by the agent.
      bug_report_id: The UUID/ID of the corresponding bug report in the database.
  """
  payload = {"event_type": "user_issue", "report": issue_report, "bug_report_id": bug_report_id}
  producer = create_kafka_producer()
  async with producer:
    value = json.dumps(payload).encode("utf-8")
    await send_kafka_value(producer, topic, value)
  return f"Successfully sent issue report to topic '{topic}'"
