import logging
import os

import aiohttp

from agent.kafka_tool import send_issue_to_redpanda

logger = logging.getLogger(__name__)


async def process_user_issue(
  user_description: str, telemetry_context: dict, bug_report_id: str | None = None
):
  api_key = os.environ.get("GOOGLE_API_KEY")
  if not api_key:
    raise ValueError("GOOGLE_API_KEY environment variable not set")

  url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={api_key}"

  system_prompt = """You are an AI assistant that analyzes user-reported issues and telemetry data.
Analyze the user's issue and how it might relate to the telemetry data provided.
Format a clean, detailed report summarizing the issue, potential root causes, and relevant context.
You MUST use the 'send_issue_to_redpanda' tool to send the report to the 'user-issues' topic.
Make sure to pass the provided bug_report_id to the tool call.
Respond with a brief summary of what you did.
"""

  user_message = f"User Issue Description: {user_description}\nTelemetry Defaults/Context: {telemetry_context}\nBug Report Database ID: {bug_report_id}"

  tools = [
    {
      "functionDeclarations": [
        {
          "name": "send_issue_to_redpanda",
          "description": "Sends a formatted issue report to a specific Redpanda topic.",
          "parameters": {
            "type": "OBJECT",
            "properties": {
              "topic": {"type": "STRING", "description": "The topic name (e.g., 'user-issues')."},
              "issue_report": {
                "type": "STRING",
                "description": "The stringified report generated by the agent.",
              },
              "bug_report_id": {
                "type": "STRING",
                "description": "The UUID/ID of the corresponding bug report in the database.",
              },
            },
            "required": ["topic", "issue_report"],
          },
        }
      ]
    }
  ]

  payload = {
    "systemInstruction": {"parts": [{"text": system_prompt}]},
    "contents": [{"role": "user", "parts": [{"text": user_message}]}],
    "tools": tools,
    "generationConfig": {"temperature": 0.0},
  }

  async with aiohttp.ClientSession() as session:
    # Initial call
    async with session.post(url, json=payload) as resp:
      if resp.status != 200:
        error_text = await resp.text()
        logger.error("Gemini API error %s: %s", resp.status, error_text[:500])
        raise Exception(f"Gemini API Error: {error_text}")

      data = await resp.json()

    # Process response defensively (Gemini may block or change shape)
    candidates = data.get("candidates") or []
    if not candidates:
      finish_reason = (data.get("promptFeedback") or {}).get("blockReason")
      if finish_reason:
        logger.warning("Gemini blocked the response: %s", finish_reason)
      return "Agent failed to generate a response (no candidates)."

    try:
      parts = candidates[0].get("content", {}).get("parts") or []
    except Exception:
      parts = []

    for part in parts:
      fc = part.get("functionCall") or {}
      if fc.get("name") == "send_issue_to_redpanda":
        args = fc.get("args", {}) or {}
        await send_issue_to_redpanda(
          topic=args.get("topic", "user-issues"),
          issue_report=args.get("issue_report", ""),
          bug_report_id=args.get("bug_report_id") or bug_report_id,
        )
        return f"Analyzed issue and successfully dispatched report to Redpanda topic '{args.get('topic', 'user-issues')}'."

    # Fallback if no tool was called
    if parts and isinstance(parts[0], dict) and "text" in parts[0]:
      return parts[0]["text"]

    logger.info("Agent did not invoke the Redpanda tool; returning text fallback if any.")
    return "Agent processed the issue but did not dispatch to Redpanda."
